# Generated by Django 5.0.6 on 2024-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'MANAGER'), ('qa', 'QA'), ('developer', 'DEVELOPER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('review', 'REVIEW'), ('working', 'WORKING'), ('aqaiting release', 'AWAITINGREL'), ('qaiting qa', 'WAITINGQA')], max_length=100),
        ),
    ]
