# Generated by Django 5.0.6 on 2024-07-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_timeline_delete_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='is_read',
        ),
    ]
