### User Registration API
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{ 
    "username": "Rohan", 
    "password": "Riffat@1100", 
    "confirm_password" : "Riffat@1100",
    "profile" : {
        "role": "qa", 
        "contact_number": "3439887746764"
    }
}


### User Login API
POST http://127.0.0.1:8000/api/api/token/
Content-Type: application/json

{ 
    "username": "rehan", 
    "password": "Riffat@1100"
}


### User Logout API
POST http://127.0.0.1:8000/api/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTE0OTE5LCJpYXQiOjE3MjE5MTQ2MTksImp0aSI6IjcxYjlmZTIwMWM1NTRmOWJhNzc1YmZiOTEzZWI2ZjQ0IiwidXNlcl9pZCI6N30.Pg83FmLMx8zQE1LdwmSqKQ3SCnSceztJapCRRflz8mE
Content-Type: application/json

{ "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMjAwMTAxOSwiaWF0IjoxNzIxOTE0NjE5LCJqdGkiOiIxOGMzMDE5NTc2MjY0ZDQwYTk5YTVkYTQwYzgxOTk4MyIsInVzZXJfaWQiOjd9.RkJG2U2Hx3AC4G_zMIrYuGIeH5Z92aywnz_To3yF7Dw"}


### Register Project API
POST http://127.0.0.1:8000/api/projects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTM3MTcwLCJpYXQiOjE3MjE5MzY4NzAsImp0aSI6IjdiODI4YzJjNmE4ODQ0YjI4Y2JkNDhmYzY1YTcyOTA2IiwidXNlcl9pZCI6MTB9.dXw46aMIsOUoggnVjrdDjgCMIfqIDl2sb4WLL_l-mjs
Content-Type: application/json

{
    "title" : "Django advance Topics",
    "description" : "Make separate git rep and add me in it",
    "start_date" : "2024-07-27",
    "end_date" : "2024-08-07",
    "team_members" : [1,5]
}


### Get all Project API
GET http://127.0.0.1:8000/api/projects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTI4NzgwLCJpYXQiOjE3MjE5Mjg0ODAsImp0aSI6ImM0NjQ5NDdmMWIyYzQxNWY5NGU3YjE2YTQ1MGVmZWRlIiwidXNlcl9pZCI6NH0.8xoNxvcgLYSSl2Us2C-I4I5TqHmweZUfAoCDxpmKZZ8



### Get Project API
GET http://127.0.0.1:8000/api/projects/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTI5MjQxLCJpYXQiOjE3MjE5Mjg5NDEsImp0aSI6ImZmZmFjNWEwM2YwMDQ0YzI4ZDlkMTBiYjg1MDVjOTQ5IiwidXNlcl9pZCI6Mn0.VPFBSmUOU7VHrWmW8XT9LIernqsq3mC1KU1QRHAVLFo

### Update Project API
PUT http://127.0.0.1:8000/api/projects/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTM3MjQ0LCJpYXQiOjE3MjE5MzY5NDQsImp0aSI6ImFiZGYxMDcxZGM2MjQ4Y2M4NGIwYWIyZmE3Mzk0MWQyIiwidXNlcl9pZCI6NH0.bnORRP6nOZ62N_T3SY-XDj-IzbuPrwISJ0VdGQxJ9T8
Content-Type: application/json

{
    "title" : "Updated Title"
}


### Create Task API
POST http://127.0.0.1:8000/api/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTA4NDk0LCJpYXQiOjE3MjE5MDgxOTQsImp0aSI6IjllMWRjMDBmYzQ3MzRkZTZhNTY2ZGNmNDc0M2RmNDM2IiwidXNlcl9pZCI6N30.8prhhz-wpZMngpQUWgqQoYklSwsFA0Mi9dSjy5117e0
Content-Type: application/json

{
  "title": "new task",
  "description": "deleted",
  "status": "review",
  "project": 1,
  "assignee": 5
}


### Task DEtail API
GET http://127.0.0.1:8000/api/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODM3MjE5LCJpYXQiOjE3MjE4MzY5MTksImp0aSI6ImI1YmY0YzVjOTcwYTQ5MWZiY2M5NjlhNmM2NzIyMWViIiwidXNlcl9pZCI6N30.J5ym6Cyoc5sSPNC_iKKDdUIDq7eJ5kv9g00IHeWoKZk



### Task Detail API
GET http://127.0.0.1:8000/api/tasks/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODI5ODY2LCJpYXQiOjE3MjE4Mjk1NjYsImp0aSI6IjAxZWY0MWMyMmNmYzRmNDM5MWFiMTM1MDYyMWNkYmJkIiwidXNlcl9pZCI6N30.wg0a7sv4cWMaNh0ht_QR1vqvVDiw7pBASQl8soOQsjY


### Update
PUT http://127.0.0.1:8000/api/tasks/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODMwMzkyLCJpYXQiOjE3MjE4MzAwOTIsImp0aSI6IjRiOGU3ZDc5MTlmMzQ4ZmVhMTY0ZDU2OGZjOWVjMTc3IiwidXNlcl9pZCI6N30.U1oQT1segFSn25W9ETnmlG2vClBHC4AuUElf68FJYvA
Content-Type: application/json

{
  "status": "working",
  "assignee": "5"
}


### DElete
DELETE http://127.0.0.1:8000/api/tasks/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODIwNjk5LCJpYXQiOjE3MjE4MjAzOTksImp0aSI6IjU1NDljZDllMTgxYzQ5NjZhM2VhODE0M2JlMjMzZTViIiwidXNlcl9pZCI6N30.1dq97Airj2CkpJmBuCHjjjL_8UhVWxBrQA_Q-l1j8-U


### Assign task
POST http://127.0.0.1:8000/api/tasks/4/assign/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODI2NjAzLCJpYXQiOjE3MjE4MjYzMDMsImp0aSI6IjcxNWM5MDA0NTM5MjQxZDlhOWIyNDlhZTdlNWEyMTQ2IiwidXNlcl9pZCI6N30.kUYdBHEkowoUDTb7WXInigaoK8dddm7kT3e-HGDJBv4


### Upload Document API
POST http://127.0.0.1:8000/api/documents/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTA1MTUwLCJpYXQiOjE3MjE5MDQ4NTAsImp0aSI6IjIzOGU3MjY0MzgwMTRiNDFiNmRiMDllNzU3NzMyMzQ4IiwidXNlcl9pZCI6N30.V-JOPCgEqwghVxMM3wgz0iU5mLSwDMwTBj6MQLyUGHo
Content-Type: application/json

{
    "name" : "APIs with ModelViewSet",
    "description" : "Project of the api- userauthentication",
    "version" : ".py",
    "project" : 2
}


### Get ALL Document API
GET http://127.0.0.1:8000/api/documents/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODM4MzkyLCJpYXQiOjE3MjE4MzgwOTIsImp0aSI6IjY2OWU5OWIyN2IzMTQwMjhhMzJlNTJmMWU3OTQyODlhIiwidXNlcl9pZCI6N30.qAJraqwwOF78dhr-JjrueYom7kcu68WQXqkXmO1jtck


### Get Document API
GET http://127.0.0.1:8000/api/documents/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODI5MzIyLCJpYXQiOjE3MjE4MjkwMjIsImp0aSI6IjUzYTg3ZmZhOTExNjQ5NDVhMzRmODA5MmYwMzRmZGQxIiwidXNlcl9pZCI6N30.KDBx6ewXfK1Hx44NnVZ6E_90LT13w-bvOWZf0xwjCbw


### Update Document API
PUT http://127.0.0.1:8000/api/documents/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxODMwMzkyLCJpYXQiOjE3MjE4MzAwOTIsImp0aSI6IjRiOGU3ZDc5MTlmMzQ4ZmVhMTY0ZDU2OGZjOWVjMTc3IiwidXNlcl9pZCI6N30.U1oQT1segFSn25W9ETnmlG2vClBHC4AuUElf68FJYvA
Content-Type: application/json

{
    "name" : "Updateddd"
}


### Upload Comment API
POST http://127.0.0.1:8000/api/comments/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTE5OTU4LCJpYXQiOjE3MjE5MTk2NTgsImp0aSI6IjBmNjYyNDk4ZTlmNTRjMDk5MjUwNDYzNDJmODViODQ0IiwidXNlcl9pZCI6M30.cH1d445Xn8MSgYcnGSoHVQrOoPa04ndnC8z8i2ozXM4
Content-Type: application/json

{
    "text" : "Review the comments!",
    "author" : 2,
    "project" : 1,
    "task" : 1
}


### Get ALL Comments API
GET http://127.0.0.1:8000/api/comments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTE5NjcxLCJpYXQiOjE3MjE5MTkzNzEsImp0aSI6IjQyYjhkYzhkOTNmMTQ0YjA5M2I2OTU3ODU3NzcyM2M5IiwidXNlcl9pZCI6M30.pDOO2N-ysEZloHYTllipjnu8dEgIP5WH05FpUNgbE_I

### Get Comment API
GET http://127.0.0.1:8000/api/comments/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTA0Mjk4LCJpYXQiOjE3MjE5MDM5OTgsImp0aSI6IjM4OGZhOTEwYmJlYzQ2MjRhMTZmZGJiZDY0MGYyN2FmIiwidXNlcl9pZCI6N30.6w6r_mtd-xunerKib-zfDQorR6H2M8T9hKz9Xhz2-N8


### Update Comment API
PUT http://127.0.0.1:8000/api/comments/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxOTA0Mjk4LCJpYXQiOjE3MjE5MDM5OTgsImp0aSI6IjM4OGZhOTEwYmJlYzQ2MjRhMTZmZGJiZDY0MGYyN2FmIiwidXNlcl9pZCI6N30.6w6r_mtd-xunerKib-zfDQorR6H2M8T9hKz9Xhz2-N8
Content-Type: application/json

{
    "text" : "Invalid text"
}